[2025-01-30T00:00:06.675+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T00:00:06.680+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-01-30T00:00:06.683+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-01-30T00:00:06.683+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T00:00:06.687+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-01-29 00:00:00+00:00
[2025-01-30T00:00:06.690+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T00:00:06.690+0000] {standard_task_runner.py:72} INFO - Started process 1125 to run task
[2025-01-30T00:00:06.691+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'scheduled__2025-01-29T00:00:00+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpx0orxuzb']
[2025-01-30T00:00:06.692+0000] {standard_task_runner.py:105} INFO - Job 403: Subtask load_weather_data
[2025-01-30T00:00:06.718+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data scheduled__2025-01-29T00:00:00+00:00 [running]> on host 10ad9b47e333
[2025-01-30T00:00:06.763+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-29T00:00:00+00:00'
[2025-01-30T00:00:06.764+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T00:00:06.764+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T00:00:06.764+0000] {logging_mixin.py:190} INFO - Current task name:load_weather_data state:running start_date:2025-01-30 00:00:06.680886+00:00
[2025-01-30T00:00:06.764+0000] {logging_mixin.py:190} INFO - Dag name:weather_etl_pipeline and current dag run status:running
[2025-01-30T00:00:06.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T00:00:06.769+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2025-01-30T00:00:06.773+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T00:00:06.777+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T00:00:06.777+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=scheduled__2025-01-29T00:00:00+00:00, execution_date=20250129T000000, start_date=20250130T000006, end_date=20250130T000006
[2025-01-30T00:00:06.780+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T00:00:06.781+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T00:00:06.781+0000] {logging_mixin.py:190} INFO - Dag name:weather_etl_pipeline queued_at:2025-01-30 00:00:00.903091+00:00
[2025-01-30T00:00:06.781+0000] {logging_mixin.py:190} INFO - Task hostname:10ad9b47e333 operator:_PythonDecoratedOperator
[2025-01-30T00:00:06.790+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T00:00:06.798+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T00:00:06.799+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
